import React, { useState } from "react";
import ExampleCards from "./ExampleCards";
import ExampleLogComponent from "./ExampleLogComponent";
import ToggleButton from "@mui/material/ToggleButton";
import ToggleButtonGroup from "@mui/material/ToggleButtonGroup";
import ChatGPTExamples from "./ChatGPTExamples";
import Tooltip from "@mui/material/Tooltip";

const Examples = () => {
  const [currentExample, setCurrentExample] = useState(0);
  const [alignment, setAlignment] = useState("Standard");
  const handleChange = (event, newAlignment) => {
    if(newAlignment) setAlignment(newAlignment);
  };

  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "column",
        marginTop: "2vh",
      }}
    >
      <ToggleButtonGroup
        color="primary"
        value={alignment}
        exclusive
        onChange={handleChange}
        aria-label="Platform"
        style={{ marginBottom: "2vh" }}
      >
        <Tooltip title="Those diagrams were generated by ChatGPT" placement="left">
          <ToggleButton value="Chat-GPT" color="primary" style={alignment === 'Chat-GPT' ? {color: '#1976d2'} : undefined}>Chat-GPT</ToggleButton>
        </Tooltip>
        <Tooltip title="Those diagrams were generated by human" placement="right"> 
          <ToggleButton value="Standard" color="primary" style={alignment === 'Standard' ? {color: '#1976d2'} : undefined}>Standard</ToggleButton>
        </Tooltip>
      </ToggleButtonGroup>
      {alignment === "Standard" && (
        <>
          <ExampleCards
            currentExample={currentExample}
            setCurrentExample={setCurrentExample}
          />
          <ExampleLogComponent currentExample={currentExample} />
        </>
      )}
      {alignment === "Chat-GPT" && <ChatGPTExamples />}
    </div>
  );
};

export default Examples;

export const examplesData = [
  {
    filePath: "examples/BookLendingExample.bpmn",
    description: "BPMN diagram describes library lending process. ",
    bpmnID: 0,
    title: "Book Lending",
    imgPath: "./images/book.jpg",
  },
  {
    filePath: "examples/BookingExample.bpmn",
    description:
      "This is a booking process that involves booking travel activities.",
    bpmnID: 1,
    title: "Booking",
    imgPath: "./images/travel.jpg",
  },
  {
    filePath: "examples/CashMaschineExample.bpmn",
    description:
      " Following example contatins process of cash flow in ATM cash maschine. ",
    bpmnID: 2,
    title: "Cash Machine",
    imgPath: "./images/cashMachine.jpg",
  },
  {
    filePath: "examples/OnlineShopExample.bpmn",
    description: " Diagram contains process of placing order in online shop. ",
    bpmnID: 3,
    title: "Online Shop",
    imgPath: "./images/onlineShop.jpg",
  },
  {
    filePath: "examples/PizzaOrderingExample.bpmn",
    description: "Ordering pizza in restaurant described by BPMN. ",
    bpmnID: 4,
    title: "Pizza Ordering",
    imgPath: "./images/pizza.jpg",
  },
];
